// Importante verificar el puerto (estos son los que estaba utilizando yo)
// iis
@NativoChallenge.WebAPI_HostAddress = https://localhost:44378
//docker
//@NativoChallenge.WebAPI_HostAddress = https://localhost:49153

## Auth - JWT Bearer Token
// Replace with actual token when needed
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiI0OWJmZGVjMi0wMjExLTQ0N2ItYWMzYy00MDBjZDU0NWM4ODYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc0OTY3OTExOSwiaXNzIjoiTmF0aXZvQ2hhbGxlbmdlLm5ldCIsImF1ZCI6ImxvY2FsaG9zdCJ9.TDTGiGpW550IpEv9E1JMLoIysrSvbR5KH-FMzolnGGs
POST {{NativoChallenge.WebAPI_HostAddress}}/auth/token
Content-Type: application/json

{
  "userName": "admin",
  "password": "Admin123!"
}


### Task Endpoints --

### Get All Tasks
GET {{NativoChallenge.WebAPI_HostAddress}}/tasks
Authorization: {{token}}

### Get Task with Pending state with default order
GET {{NativoChallenge.WebAPI_HostAddress}}/tasks?State=Pending
Authorization: {{token}}

### Get All Task order by Priority
GET {{NativoChallenge.WebAPI_HostAddress}}/tasks?OrderBy=Priority
Authorization: {{token}}

### Get Task with Pending state by Priority
GET {{NativoChallenge.WebAPI_HostAddress}}/tasks?State=Pending&OrderBy=Priority
Authorization: {{token}}

### Create New Task
POST {{NativoChallenge.WebAPI_HostAddress}}/tasks
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Terminar desafío",
  "description": "Completar el challenge técnico",
  "expirationDate": "2027-06-10T00:00:00Z",
  "priority": "High"
}

### Complete Task
PUT {{NativoChallenge.WebAPI_HostAddress}}/tasks/{{taskId}}/complete
Authorization: {{token}}

### Delete Task
DELETE {{NativoChallenge.WebAPI_HostAddress}}/tasks/{{taskId}}
Authorization: {{token}}